### PR TITLE
doxygen

### PR DESCRIPTION
**Pull request by makelinux**

### CODE REVIEW

**Comment by makelinux** [comment]
@MathieuDuponchelle , @sdroege

**Comment by MathieuDuponchelle** [comment]
@makelinux I don't think there's much of a point for adding a documentation infrastructure to what is only a set of demo applications. If there was, most contributors to that project are usually more familiar with gtk-doc style comments in any case :)

**Comment by makelinux** [comment]
First of all thank you for examples.
You are missing the point. I am as newcomer was very confused by numerous examples without clean explanation what difference is.
You are welcome to convert it to gtk-doc.

**Comment by nirbheek** [comment]
The way to fix that would be to update the README.md which hasn't been updated in a very long time.

**Comment by makelinux** [comment]
Yes, there is an option to update README.md. But it is less scalable. And again it will be outdated for a long time.

Comments in files are more easy to keep updated.
Doxygen automatically lists files with **@file @brief** messages on a sub page. For example: https://www.unidata.ucar.edu/software/ldm/ldm-current/utilities/noaaport/files.html
Can gtk-doc it?

**Comment by ystreet** [comment]
These examples have moved to https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc and this repository will not be updated further.

**Pull request closed without merging**
