### PR TITLE
fix #42: 'Structure' object is not subscriptable

### LINKED ISSUE #42: webrtc-sendrecv.py TypeError : 'Structure' object is not subscriptable
I am able to successfully test out the stream from C version, but not the python version. I have modified [this docker file](https://github.com/maxmcd/gstreamer-docker/blob/master/1.14/buster/Dockerfile) to setup gstreamer 1.14.2.

```
root@bcc8369cc4db:/gstwebrtc-demos# python3 sendrecv/gst/webrtc-sendrecv.py 7729
Traceback (most recent call last):

File "sendrecv/gst/webrtc-sendrecv.py", line 53, in on_offer_created

offer = reply['offer']

TypeError: 'Structure' object is not subscriptable

```
Thanks.

### PR DESCRIPTION
**Pull request by hexray-newbee**

### CODE REVIEW

**Comment by ichernev** [comment]
This patch is critical for anyone trying to run the python webrtc example (under python3 and latest everything).
@MathieuDuponchelle can you please consider merging?

**Comment by thaytan** [comment]
This happens if you don't have the gst-python bindings, which provide overrides to the basic gobject-introspection binding

**Comment by ichernev** [comment]
And how are these bindings installed/required? The folder could include a requirements file (for pip), for easier setup, I already had some trouble figuring out `gi`.

**Comment by sdroege** [comment]
You can find the source code here: https://gstreamer.freedesktop.org/src/gst-python/

I don't think it's available from pip, but someone more knowledgeable with Python might be able to help here.

**Comment by ystreet** [comment]
The examples target the use of gst-python.  There are other examples in other languages if the python one does not work for you without gst-python.

**Pull request closed without merging**
