### PR TITLE
Implement the demo in C# with GStreamerSharp

### PR DESCRIPTION
**Pull request by thiblahute**
Based on https://github.com/ttustonic/GStreamerSharpSamples from
Tomislav Tustonić <ttustonic@outlook.com>

### CODE REVIEW

**Comment by thiblahute** [comment]
Also, ooc, why don't those demo go into gst-plugins-bad?

**Comment by ystreet** [comment]
This has some interesting formatting and inconsistent indenting.  It could also do with some comments and/or FIXME's about what a user may need to change or look out for but that's not quite so critical for merging.

**Comment by thiblahute** [comment]
> This has some interesting formatting and inconsistent indenting. It could also do with some comments and/or FIXME's about what a user may need to change or look out for but that's not quite so critical for merging.

Indeed, let me fix tab vs space issues (I think this is where indentation issue comes from).

**Comment by thiblahute** [comment]
Updated fixing indentation,

**Pull request merged**
